# -----------------------------------------------------------------------------
# Application Configuration
# -----------------------------------------------------------------------------
app:
  tz: "Asia/Jakarta"
  server:
    address:
      http: "0.0.0.0:8080"

# -----------------------------------------------------------------------------
# Modules Configuration
# -----------------------------------------------------------------------------
modules:
  book-cabin:
    enabled: true
    cache:
      ttl_seconds: 60
    provider:
      rate_limit_ms: 100
